### ISSUE TITLE
Error: could not find function "echartsExample"

### ISSUE THREAD

**Issue by LalZzy** [cosname/recharts#48]
你好，阅读recharts包在线文档，我有个小问题。
帮助文档中有提到用echartsExample函数执行原生js代码，包中现在是不包含这个函数了吗？

**Comment by Lchiffon** [comment]
目前看到的在线文档是开发版的请这样安装:
```r
require(devtools)
devtools::install_github("cosname/recharts@dev")
```

**Comment by LalZzy** [comment]
`require(devtools)
devtools::install_github("cosname/recharts@dev")`

`Error in utils::unzip(src, exdir = target) : 
  invalid multibyte string at '<a3>.<52>md'`

**Comment by Lchiffon** [comment]
诶呦我去, 好像是一个windows才会出现的问题, 容小的看下...

**Comment by Lchiffon** [comment]
文档里面文件的中文名问题, 已经修改好了, 童鞋您再试试?
@LalZzy

**Comment by LalZzy** [comment]
可以了，感谢朗大大！
