### ISSUE TITLE
eBar的stackGroup参数无法实现效果

### ISSUE THREAD

**Issue by chriswweibo** [cosname/recharts#50]
以前有一个stack=T可以用，现在想通过stackGroup(unique(组名))，实现堆叠，可是不行。

**Comment by Lchiffon** [comment]
恩恩, 这是因为E2切到E3之后有些参数变了, 我目前更新的dev分支已经修复这个问题了.

安装代码用:

```r
require(devtools)
devtools::install_github("cosname/recharts@dev")
```

文档见: 
http://recharts.cosx.org/basefunction#section-6.3


![image](https://user-images.githubusercontent.com/7221728/29500177-c04add84-8650-11e7-8a63-8f315c93f8dd.png)

**Comment by chriswweibo** [comment]
谢谢，OK了。
功德无量。
